### ISSUE TITLE
Costs going into decimals

### ISSUE THREAD

**Issue by KuraTheDog** [benediktwerner/vampire-survivors-power-up-calculator#4]
I don't recall which way the game goes (pretty sure not decimal, but I think it rounds up?), but curse total cost is going into decimals.
E.g. revival, then 1 curse: 10,000 for revive, then "1832.6" for 1 level of curse. Total ends up as "11832.6".
(Won't matter most likely as it's at most 4 gold difference I think which is insignificant, but I think it's technically wrong)

**Comment by benediktwerner** [comment]
Good point, I completely forgot about this. But actually, the game does store decimal coins, also for stuff like the greed multiplier. It just cuts off the decimals when displaying the amount.

This means with greed now the calculator can never actually tell everybody the exact true cost since it depends on their hidden decimal coins.

I think leaving it as is and showing the actual cost even if the game won't show it is the most correct.
